import { TextStyle, ViewStyle } from 'react-native';

export type Styles = {
  button: ViewStyle;
  buttonContainer: TextStyle;
  buttonBottomContainer: TextStyle;
  buttonTitle: TextStyle;
  buttonDisabled: ViewStyle | TextStyle;
  buttonOutline: ViewStyle;
  buttonOutlineTitle: TextStyle;
  buttonOutlineDisabled: ViewStyle | TextStyle;
  buttonInvScreenHeader: ViewStyle;
  buttonInvScreenHeaderTitle: TextStyle;
  buttonInvScreenHeaderDisabled: ViewStyle | TextStyle;
  buttonScreenHeader: ViewStyle;
  buttonScreenHeaderTitle: TextStyle;
  buttonScreenHeaderDisabled: ViewStyle | TextStyle;
  listEmptyText: TextStyle;
  listItemContainer: ViewStyle;
  listItemBorder: ViewStyle;
  listItemTitle: TextStyle;
  listItemSubtitle: TextStyle;
  listItemValue: TextStyle;
  navigationBottomTabBar: ViewStyle;
  textDim: TextStyle;
  textHeading1: TextStyle;
  textHeading2: TextStyle;
  textHeading3: TextStyle;
  textHeading4: TextStyle;
  textLarge: TextStyle;
  textLink: TextStyle;
  textNormal: TextStyle;
  textPlaceholder: TextStyle;
  textSmall: TextStyle;
  textTiny: TextStyle;
  textXL: TextStyle;
  view: ViewStyle;
  viewAlt: ViewStyle;
};
