import { createTheme } from '@rneui/themed';
import lodash from 'lodash';
import { theme as rneulTheme } from '@react-native-hello/ui';

export const theme = createTheme(
  lodash.merge({}, rneulTheme, {
    darkColors: {
      activeTabBackground: '#202020',
      activityIndicator: '#ffffff',
      activityIndicatorInv: '#0078fe',
      androidNavigationBar: '#101010',
      assertive: '#ff1f1f',
      black: '#f2f2f2',
      button: '#0078fe',
      buttonText: '#ffffff',
      checkboxActive: '#0078fe',
      checkboxInactive: '#0078fe',
      collapsibleBackground: '#000000',
      datePicker: '#0078fe',
      divider: '#0d101f',
      dropdown: '#303030',
      dropdownSelection: '#545454',
      dropdownIconNav: '#ffffff',
      listItem: '#303030',
      listItemAlt: '#000000',
      listItemBorder: '#1b1b1b',
      listItemIcon: '#0078fe',
      listItemIconNav: '#ffffff',
      listHeaderBackground: '#000000',
      listHeaderTextBackground: '#000000',
      screenHeaderBackground: '#202020',
      screenHeaderButtonText: '#ffffff',
      screenHeaderTitle: '#ffffffde',
      segmentActive: '#787878',
      segmentBackground: '#1a1a17',
      segmentBorder: '#303030',
      switchOffThumb: '#ffffff',
      switchOffTrack: '#787878',
      switchOnThumb: '#ffffff',
      switchOnTrack: '#0078fe',
      tabBarActive: '#0078fe',
      tabBarActiveBackground: '#202020',
      tabBarBorder: '#1b1b1b',
      tabBarInactive: '#787878',
      tabBarInactiveBackground: '#202020',
      text: '#ffffff',
      textDim: '#878787',
      textInputBorderColor: '#4e5270',
      textInv: '#000000',
      textLight: '#878787',
      textLink: '#0078fe',
      textLinkInv: '#ffffffde',
      textPlaceholder: '#878787',
      viewBackground: '#202020',
      viewAltBackground: '#1b1b1b',
    },
    lightColors: {
      activeTabBackground: '#ffffff',
      activityIndicator: '#000000',
      activityIndicatorInv: '#ffffff',
      androidNavigationBar: '#f0f0f0',
      assertive: '#ff1f1f',
      black: '#000000',
      button: '#0078fe',
      buttonText: '#ffffff',
      checkboxActive: '#0078fe',
      checkboxInactive: '#0078fe',
      collapsibleBackground: '#f0f0f0',
      datePicker: '#0078fe',
      divider: '#0d101f',
      dropdown: '#ffffff',
      dropdownSelection: '#e5e5e5',
      dropdownIconNav: '#000000',
      listItem: '#ffffff',
      listItemAlt: '#f0f0f0',
      listItemBorder: '#e5e5e5',
      listItemIcon: '#0078fe',
      listItemIconNav: '#000000',
      listHeaderBackground: '#f0f0f0',
      listHeaderTextBackground: '#f0f0f0',
      screenHeaderBackground: '#ffffff',
      screenHeaderButtonText: '#000000',
      screenHeaderTitle: '#000000',
      segmentActive: '#ffffff',
      segmentBackground: '#e2e1e6',
      segmentBorder: '#d5d4d9',
      switchOffThumb: '#ffffff',
      switchOffTrack: '#f2f2f2',
      switchOnThumb: '#ffffff',
      switchOnTrack: '#0078fe',
      tabBarActive: '#0078fe',
      tabBarActiveBackground: '#ffffff',
      tabBarBorder: '#aaaaaa',
      tabBarInactive: '#aaaaaa',
      tabBarInactiveBackground: '#ffffff',
      text: '#303030',
      textDim: '#aaaaaa',
      textInputBorderColor: '#4e5270',
      textInv: '#ffffff',
      textLight: '#787878',
      textLink: '#0078fe',
      textLinkInv: '#ffffff',
      textPlaceholder: '#878787',
      viewBackground: '#f2f2f2',
      viewAltBackground: '#ffffff',
    },
  }),
);
